### ISSUE TITLE
hgetall broken?

### ISSUE THREAD

**Issue by ghost** [jcmellado/dartis#21]
Hello, I was using dartis in a project and I run into the problem that when I try to use hgetall dart crash.

Code:
```dart
    final redis = await Client.connect('redis://localhost:6379');
    final cmd = redis.asCommands<String, dynamic>();
    final result = await cmd.hgetall('test');
    print(result);
```

Error:
```
Unhandled exception:
RedisException: Unexpected value of type "BulkReply".
#0      _MultiConverter.convert (package:dartis/src/protocol/codec.dart:95:5)
#1      RedisCodec.decode (package:dartis/src/protocol/codec.dart:65:41)
#2      HashMapper.map (package:dartis/src/commands/hash.dart:163:27)
#3      CommandBase._complete (package:dartis/src/command/command.dart:91:20)
#4      CommandBase.complete (package:dartis/src/command/command.dart:65:19)
#5      _ClientDispatcher.onReply (package:dartis/src/client/client.dart:260:15)
#6      ReplyDispatcher._dispatch (package:dartis/src/client/dispatcher.dart:90:7)
#7      ReplyDispatcher.onData (package:dartis/src/client/dispatcher.dart:78:9)
#8      _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#9      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#10     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#11     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#12     _StreamController._add (dart:async/stream_controller.dart:639:7)
#13     _StreamController.add (dart:async/stream_controller.dart:585:5)
#14     _Socket._onData (dart:io/runtime/binsocket_patch.dart:1721:41)
#15     _RootZone.runUnaryGuarded (dart:async/zone.dart:1314:10)
#16     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
#17     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
#18     _SyncStreamController._sendData (dart:async/stream_controller.dart:763:19)
#19     _StreamController._add (dart:async/stream_controller.dart:639:7)
#20     _StreamController.add (dart:async/stream_controller.dart:585:5)
#21     new _RawSocket.<anonymous closure> (dart:io/runtime/binsocket_patch.dart:1283:33)
#22     _NativeSocket.issueReadEvent.issue (dart:io/runtime/binsocket_patch.dart:826:14)
#23     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#24     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#25     _runPendingImmediateCallback (dart:isolate/runtime/libisolate_patch.dart:115:13)
#26     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:172:5)
```

**Comment by jcmellado** [comment]
You are using `dynamic` as type of the values stored in Redis:

`final cmd = redis.asCommands<String, dynamic>();`

But `dynamic` is not a "concrete" type, so the library doesn't known how to deserialize the values.

Take a look to this section of the documentation about how to write custom serializers/deserializers:

https://github.com/jcmellado/dartis#custom-serializersdeserializers

**Comment by ghost** [comment]
@jcmellado
I'm using dynamic since the hash that I'm using has different types
Ex:
```
  HSET test test_int 0
  HSET test test_str "test test"
```

and I hope to get something like that:
``` 
  HGETALL test
```
```
  Dart Map = {
    'test_int': 0,
    'test_str': 'test test'
  }
```
and not like that (for example with redis.asCommands<String, String>)
```
  Dart Map = {
    'test_int': '0',
    'test_str': 'test test'
  }
```
Is it possible to make the library work like this? I think it would be a good idea to make an exception to the strict typing for the hashes.

A work around would be to make an hget for each field and declaring the type with `redis.asCommands <String, *fieldtype*>();`, but I think that it's not a good practice.

**Comment by jcmellado** [comment]
All the values are stored in Redis as strings (arrays of bytes). It's necessary to specify a concrete type to decode them (target type).

If the types of the values stored in Redis are unknown (maybe they are populated from an external source) then a custom decoder could be writen.

For example, the following decoder works with `String` and `int`, it's very simple but you'll get the idea:

```dart
class DynamicDecoder extends Decoder<Reply, dynamic> {
  @override
  dynamic convert(Reply reply, [RedisCodec codec]) {
    final value = codec.decode<String>(reply);

    return int.tryParse(value) ?? value;
  }
}
```

And then:

```dart
  client.codec.register(decoder: DynamicDecoder());

  final commands = client.asCommands<String, dynamic>();

  await commands.hmset('test', hash: <String, dynamic>{'a': 1, 'b': 'xyz'});

  final map = await commands.hgetall('test');

  print(map['a'] is int); // true
  print(map['b'] is String); // true
```
