### ISSUE TITLE
how to reconnect when needed?

### ISSUE THREAD

**Issue by jodinathan** [jcmellado/dartis#22]
I am starting the app, connect to a redis server, restart the redis server to break the connection, the apps try to fetch something and this is the result:

```
SocketException: OS Error: Connection reset by peer, errno = 54, address = 127.0.0.1, port = 58691
#0      _rootHandleUncaughtError.<anonymous closure> (dart:async/zone.dart:1112:29)
#1      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#2      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#3      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

However, I can't seem to catch this exception nor know before hand if the connection is broken.

How can I know when to reconnect when needed?

**Comment by jcmellado** [comment]
Take a look to the `Connection` class:
https://github.com/jcmellado/dartis/blob/master/lib/src/client/connection.dart

Extract:
```
  /// Future that is resolved when the connection is closed.
  ///
  /// If the connection closes gracefully this future will be completed and
  /// future attempts to use the connection will throw a
  /// [RedisConnectionClosedException].
  ///
  /// If the connection is broken, an error occurs writing/reading to/from the
  /// connection this future will be resolved with error. If unhandled this
  /// will propagate to the encapsulating [Zone] where it may be handled.
  /// If using the default root [Zone] this will cause the isolate to crash.
  ///
  /// If not implementing custom reconnection logic it might be desirable to
  /// simply restart the process when it crashes.
  ///
  /// If implementing custom reconnection logic, consumers should stop using a
  /// connection once [done] have been resolved, as all future commands will
  /// will throw an error. If an error occurs reading or writing all outstanding
  /// commands will be resolved with an exception.
  Future<void> get done => _done.future;
```
There some tests about that too:
https://github.com/jcmellado/dartis/blob/master/test/client/connection_test.dart

**Comment by jodinathan** [comment]
```
final connection = await dartis.Connection.connect(
        'redis://${host ?? 'localhost'}:${port}');

    unawaited(connection.done.then((err) {
      print('Redis disconnected.');

      _client = null;
    }));

    _client = await dartis.Client(connection);
```

The above snippet is not printing the message when I start the app and after stop the local redis service to break the connection.  
It shoud, right?

**Comment by oysterpack** [comment]
No - it should not. If the connection is broken, an error occurs writing/reading to/from the connection this future will be resolved with an **error**. You need to use `catchError`

```dart
connection.done.catchError((_) {
      print('Redis disconnected.');
      _client = null;
    });
```
