### ISSUE TITLE
Add support for Web

### ISSUE THREAD

**Issue by abhin-vicks** [jcmellado/dartis#33]
Getting this error when running on Web:

Error: Unsupported operation: Socket constructor
at Object.throw_ [as throw] (http://localhost:58623/dart_sdk.js:4348:11)
    at Function._connect (http://localhost:58623/dart_sdk.js:57921:17)...

**Comment by jcmellado** [comment]
The library can not be used from a browser.

AFAIK you can not connect to Redis directly from a browser.
